name: Build and attach JAR to release

on:
  release:
    types: [created]

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download library
        run: |
          curl -L -o fuel-lib.jar https://github.com/CarburoApp/fuel-station-http-library/releases/download/v1.0/fuel-station-http-library-1.0.jar

      - name: Install library
        run: |
          mvn install:install-file \
            -Dfile=fuel-lib.jar \
            -DgroupId=app.carburo.utils \
            -DartifactId=fuel-station-http-library \
            -Dversion=1.0 \
            -Dpackaging=jar

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Rename JAR
        run: mv target/LoaderCron-*.jar LoaderCron.jar

      - name: Upload JAR to release
        uses: softprops/action-gh-release@v2
        with:
          files: LoaderCron.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
